#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=920562713139
BundleId=com.kayac.realtimemultiplayerdev
ClientId=920562713139-oour4i5ie6li1n8nkrhkuuughl8glngr.apps.googleusercontent.com

*/

#define kAppID "920562713139"
#define kBundleID "com.kayac.realtimemultiplayerdev"
#define kClientID "920562713139-oour4i5ie6li1n8nkrhkuuughl8glngr.apps.googleusercontent.com"

#endif


